export const Position = {
  TOP: "top",
  BOTTOM: "bottom",
  OTHER: "other",
  HIDDEN: "hidden"
};

export const BUTTON = "BUTTON";
export const POPTEXT_ICON = "POPTEXT_ICON";
export const POPTEXT_VALUE = "POPTEXT_VALUE";
export const INCREMENTAL = "INCREMENTAL";
export const SLIDER = "SLIDER";
export const COLOR_TAB_COLOR_CHOOSER = "COLOR_TAB_COLOR_CHOOSER";
export const COLOR_TAB_WIDTH_CHOOSER = "COLOR_TAB_WIDTH_CHOOSER";

export const BUTTON_LETTER_BOLD = "BUTTON_LETTER_BOLD";
export const BUTTON_LETTER_ITALIC = "BUTTON_LETTER_ITALIC";
export const BUTTON_LETTER_UNDERLINE = "BUTTON_LETTER_UNDERLINE";

export const BUTTON_LEFT_ALIGNED = "BUTTON_LEFT_ALIGNED";
export const BUTTON_RIGHT_ALIGNED = "BUTTON_RIGHT_ALIGNED";
export const BUTTON_CENTER_ALIGNED = "BUTTON_CENTER_ALIGNED";
export const BUTTON_JUSTIFY_ALIGNED = "BUTTON_JUSTIFY_ALIGNED";
export const BUTTON_DUPLICATE = "BUTTON_DUPLICATE";

export const POPTEXT_MENU = "POPTEXT_MENU";
export const POPTEXT_LAYER = "POPTEXT_LAYER";
export const POPTEXT_VALIGN = "POPTEXT_VALIGN";
export const POPTEXT_FONT = "POPTEXT_FONT";
export const POPTEXT_IMAGE_MENU = "POPTEXT_IMAGE_MENU";

export const POPTEXT_IMAGE_SHAPE_MENU = "POPTEXT_IMAGE_SHAPE_MENU";

export const SLIDER_TEXT_SPACEING = "SLIDER_TEXT_SPACEING";
export const SLIDER_WND = "SLIDER_WND";
export const SLIDER_OPACITY_WND = "SLIDER_OPACITY_WND";
export const SLIDER_FONT_WND = "SLIDER_FONT_WND";

export const SLIDER_INLINE = "SLIDER_INLINE";

export const INCREMENTAL_FONT_SIZE = "INCREMENTAL_FONT_SIZE";

export const COLOR_SELECTOR = "COLOR_SELECTOR";
export const COLOR_SELECTOR_BACKGROUND = "COLOR_SELECTOR_BACKGROUND";

export const COLOR_SELECTOR_WND = "COLOR_SELECTOR_WND";

export const COLOR = "COLOR";
export const COLOR_TAB_FG = "COLOR_TAB_FG";
export const COLOR_TAB_BG = "COLOR_TAB_BG";
export const COLOR_TAB_BORDER_WIDTH = "COLOR_TAB_BORDER_WIDTH";
export const COLOR_TAB_BORDER_COLOR = "COLOR_TAB_BORDER_COLOR";

export const SIMPLE_ICON = "SIMPLE_ICON";
export const BUTTON_CHANGE_IMAGE = "BUTTON_CHANGE_IMAGE";
export const BUTTON_CHANGE_SHAPE = "BUTTON_CHANGE_SHAPE";

export const SPECIAL_EFFECTS_WND = "SPECIAL_EFFECTS_WND";
export const CHANGE_SHAPE_WND = "CHANGE_SHAPE_WND";

export const SLIDER_INLINE_IMAGE = "SLIDER_INLINE_IMAGE";
export const SIMPLE_ICON_QUALITY = "SIMPLE_ICON_QUALITY";
