const DAG_UPLOAD_IMAGE = "DAG_UPLOAD_IMAGE";
const DAG_UPLOAD_IMAGE_SUCCESS = "DAG_UPLOAD_IMAGE_SUCCESS";
const DAG_UPLOAD_IMAGE_FAILED = "DAG_UPLOAD_IMAGE_FAILED";

module.exports = {
  DAG_UPLOAD_IMAGE,
  DAG_UPLOAD_IMAGE_SUCCESS,
  DAG_UPLOAD_IMAGE_FAILED
};
