const CHANGE_PROJECT_TITLE = "CHANGE_PROJECT_TITLE";
const ADD_OBJECT = "ADD_OBJECT";
const ADD_OBJECT_TO_PAGE = "ADD_OBJECT_TO_PAGE";
const ADD_OBJECT_ID_TO_SELECTED = "ADD_OBJECT_ID_TO_SELECTED";
const REMOVE_SELECTION = "REMOVE_SELECTION";
const AFTER_OBJECT_MOVED = "AFTER_OBJECT_MOVED";
module.exports = {
  CHANGE_PROJECT_TITLE,
  ADD_OBJECT,
  ADD_OBJECT_TO_PAGE,
  ADD_OBJECT_ID_TO_SELECTED,
  REMOVE_SELECTION,
  AFTER_OBJECT_MOVED
};
