const CHANGE_PROJECT_TITLE = "CHANGE_PROJECT_TITLE";
const ADD_OBJECT = "ADD_OBJECT";
const ADD_OBJECT_TO_PAGE = "ADD_OBJECT_TO_PAGE";
const ADD_OBJECT_ID_TO_SELECTED = "ADD_OBJECT_ID_TO_SELECTED";
const REMOVE_SELECTION = "REMOVE_SELECTION";

const UPDATE_SELECTION_OBJECTS_COORDS = "UPDATE_SELECTION_OBJECTS_COORDS";
const UPDATE_OBJECT_PROPS = "UPDATE_OBJECT_PROPS";
const UPDATE_ACTIVE_SELECTION_PROPS = "UPDATE_ACTIVE_SELECTION_PROPS";

const UPDATE_LAYER_PROP = "UPDATE_LAYER_PROP";
const DUPLICATE_OBJ = "DUPLICATE_OBJ";
const DELETE_OBJ = "DELETE_OBJ";

module.exports = {
  CHANGE_PROJECT_TITLE,
  ADD_OBJECT,
  ADD_OBJECT_TO_PAGE,
  ADD_OBJECT_ID_TO_SELECTED,
  REMOVE_SELECTION,
  UPDATE_SELECTION_OBJECTS_COORDS,
  UPDATE_OBJECT_PROPS,
  UPDATE_ACTIVE_SELECTION_PROPS,

  UPDATE_LAYER_PROP,
  DUPLICATE_OBJ,
  DELETE_OBJ
};
