const UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET =
  "UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET";
const UI_UPDATE_CONTAINER_CANVAS_OFFSET = "UI_UPDATE_CONTAINER_CANVAS_OFFSET";
const UI_UPDATE_VIEWPORT_TRANSFORM = "UI_UPDATE_VIEWPORT_TRANSFORM";
const UPDATE_ZOOM = "UPDATE_ZOOM";
module.exports = {
  UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET,
  UI_UPDATE_CONTAINER_CANVAS_OFFSET,
  UI_UPDATE_VIEWPORT_TRANSFORM,
  UPDATE_ZOOM
};
