const ADD_IMAGE_TO_GALLERY = "ADD_IMAGE_TO_GALLERY";
const REMOVE_IMAGE_FROM_GALLERY = "REMOVE_IMAGE_FROM_GALLERY";
const ADD_PDF_TO_GALLERY = "ADD_PDF_TO_GALLERY";
const REMOVE_PDF_FROM_GALLERY = "REMOVE_PDF_FROM_GALLERY";

const SET_MOVEABLE = "SET_MOVEABLE";
const SET_RESIZABLE = "SET_RESIZABLE";
const SET_SNAP = "SET_SNAP";
const SET_ROTATE = "SET_ROTATE";

module.exports = {
  ADD_IMAGE_TO_GALLERY,
  REMOVE_IMAGE_FROM_GALLERY,
  ADD_PDF_TO_GALLERY,
  REMOVE_PDF_FROM_GALLERY,
  SET_MOVEABLE,
  SET_RESIZABLE,
  SET_SNAP,
  SET_ROTATE
};
