const ADD_IMAGE_TO_GALLERY = "ADD_IMAGE_TO_GALLERY";
const REMOVE_IMAGE_FROM_GALLERY = "REMOVE_IMAGE_FROM_GALLERY";
const ADD_PDF_TO_GALLERY = "ADD_PDF_TO_GALLERY";
const REMOVE_PDF_FROM_GALLERY = "REMOVE_PDF_FROM_GALLERY";

module.exports = {
  ADD_IMAGE_TO_GALLERY,
  REMOVE_IMAGE_FROM_GALLERY,
  ADD_PDF_TO_GALLERY,
  REMOVE_PDF_FROM_GALLERY
};
