const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
const FETCH_CLUBS = "FETCH_CLUBS";
const FETCH_CLUBS_FULFILLED = "FETCH_CLUBS_FULFILLED";
const FETCH_CLUBS_FAILED = "FETCH_CLUBS_FAILED";
const CHANGE_CURRENT_CLUB = "CHANGE_CURRENT_CLUB";
module.exports = {
  CHANGE_SEARCH_VALUE,
  FETCH_CLUBS,
  FETCH_CLUBS_FULFILLED,
  FETCH_CLUBS_FAILED,
  CHANGE_CURRENT_CLUB
};
